spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  level:
    org:
      springframework=trace:
        debug
springdoc:
  swagger-ui:
    enabled: true # swagger ui 사용여부 (굳이 설정하지 않아도 default는 true)
  version: 'v1' # API 문서 버전
  default-consumes-media-type: application/json # 기본 consume media type
  default-produces-media-type: application/json # 기본 produce media type
  model-and-view-allowed: true # ModelAndView 허용
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
server:
  servlet:
    context-path: /api/user
---
spring:
  config:
    activate:
      on-profile: prod
server:
  servlet:
    context-path: /api/user
